version: '3.8'
services:
  postgres:
    image: ankane/pgvector
    container_name: pgvector_db
    environment:
      - POSTGRES_USER=admin123
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=llm_project_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
  
volumes:
  pgdata:
    driver: local
