OPENAI_API_KEY": dummy_api_key  # only OPENAI need a real API key
OPENAI_API_BASE: http://localhost:8000/v1 
model: qwen2.5:7b
embedding_model: intfloat/multilingual-e5-large
db_connection: postgresql+psycopg://admin123:123456@localhost:5432/llm_project_db
collection_name: "speech_data"